import type { Metadata } from 'next';
import localFont from 'next/font/local';
import SessionProvider from '@/components/provider/session';
import './globals.css';
import { getServerSession } from 'next-auth';
import nextAuthOptions from '@/config/nextAuthOptions';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Gartic Aja',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession(nextAuthOptions);
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<SessionProvider session={session}>{children}</SessionProvider>
			</body>
		</html>
	);
}
